_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  mdp_size: 5
  reward_noise_precision: 1
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
mdp_size: 5
reward_noise_precision: 1
title: experience_replay=uniform; reward_noise_precision=1; mdp_size=5
