_experiment_parameters:
  experience_replay:
    __name: rank-td
    alpha: 0.95
    batch_size: 32
    sampling: rank
  mdp_size: 12
  reward_noise_precision: 1
experience_replay:
  __name: rank-td
  alpha: 0.95
  batch_size: 32
  sampling: rank
mdp_size: 12
reward_noise_precision: 1
title: experience_replay=rank-td; reward_noise_precision=1; mdp_size=12
