_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  mdp_size: 7
  reward_noise_precision: 0.01
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
mdp_size: 7
reward_noise_precision: 0.01
title: experience_replay=uniform; reward_noise_precision=0.01; mdp_size=7
