_experiment_parameters:
  experience_replay:
    __name: "rank-bayes-\u03B20.1-p0.5"
    alpha: 0.95
    batch_size: 32
    bayesian: true
    boot_beta: 0.1
    boot_no: 21
    boot_p: 0.5
    boot_shuffle: true
    sampling: rank
  mdp_size: 16
  reward_noise_precision: 0.1
experience_replay:
  __name: "rank-bayes-\u03B20.1-p0.5"
  alpha: 0.95
  batch_size: 32
  bayesian: true
  boot_beta: 0.1
  boot_no: 21
  boot_p: 0.5
  boot_shuffle: true
  sampling: rank
mdp_size: 16
reward_noise_precision: 0.1
title: "experience_replay=rank-bayes-\u03B20.1-p0.5; reward_noise_precision=0.1; mdp_size=16"
