_experiment_parameters:
  experience_replay:
    __name: greedy-pq
    batch_size: 1
    sampling: greedy-pq
  loss: mse
  mdp_size: 9
experience_replay:
  __name: greedy-pq
  batch_size: 1
  sampling: greedy-pq
loss: mse
mdp_size: 9
title: experience_replay=greedy-pq; loss=mse; mdp_size=9
