_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 1
    sampling: uniform
  loss: huber
  mdp_size: 6
experience_replay:
  __name: uniform
  batch_size: 1
  sampling: uniform
loss: huber
mdp_size: 6
title: experience_replay=uniform; loss=huber; mdp_size=6
