_experiment_parameters:
  experience_replay:
    __name: proportional
    alpha: 1
    batch_size: 1
    sampling: proportional
  loss: huber
  mdp_size: 10
experience_replay:
  __name: proportional
  alpha: 1
  batch_size: 1
  sampling: proportional
loss: huber
mdp_size: 10
title: experience_replay=proportional; loss=huber; mdp_size=10
