_experiment_parameters:
  experience_replay:
    __name: greedy-pq
    batch_size: 1
    sampling: greedy-pq
  loss: huber
  mdp_size: 8
experience_replay:
  __name: greedy-pq
  batch_size: 1
  sampling: greedy-pq
loss: huber
mdp_size: 8
title: experience_replay=greedy-pq; loss=huber; mdp_size=8
