_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 1
    sampling: uniform
  loss: mse
  mdp_size: 4
experience_replay:
  __name: uniform
  batch_size: 1
  sampling: uniform
loss: mse
mdp_size: 4
title: experience_replay=uniform; loss=mse; mdp_size=4
