mdp_size: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

loss: ['huber','mse']
experience_replay:
  - {"__name": "uniform", "sampling": "uniform", "batch_size": 1}
  - {"__name": "greedy-pq", "sampling": "greedy-pq", "batch_size": 1}
  - {"__name": "rank", "sampling": "rank", "alpha": 1, "batch_size": 32}
  - {"__name": "proportional", "sampling": "proportional", "alpha": 1, "batch_size": 1}
