mdp_size: [5, 6, 7, 8, 9, 10, 11, 12]

experience_replay:
  - {"__name": "uniform-td", "batch_size": 32, "sampling": "uniform"}

  - {"__name": "rank-bayes-Î²0.001-p0.5",
     "sampling": "rank", "batch_size": 32, "alpha": 0.95,
     "bayesian": yes, "boot_p": 0.5, "boot_no": 21, "boot_beta": 0.001,
     "boot_shuffle": yes}
