_experiment_parameters:
  experience_replay:
    __name: uniform-td
    batch_size: 32
    sampling: uniform
  mdp_size: 10
experience_replay:
  __name: uniform-td
  batch_size: 32
  sampling: uniform
mdp_size: 10
title: experience_replay=uniform-td; mdp_size=10
