_experiment_parameters:
  experience_replay:
    __name: rank
    alpha: 0.95
    batch_size: 32
    sampling: rank
  loss: huber
  mdp_size: 5
experience_replay:
  __name: rank
  alpha: 0.95
  batch_size: 32
  sampling: rank
loss: huber
mdp_size: 5
title: experience_replay=rank; loss=huber; mdp_size=5
