_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  loss: huber
  mdp_size: 15
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
loss: huber
mdp_size: 15
title: experience_replay=uniform; loss=huber; mdp_size=15
