_experiment_parameters:
  experience_replay:
    __name: rank-TD
    alpha: 0.95
    batch_size: 32
    sampling: rank
  loss: huber
  mdp_size: 13
experience_replay:
  __name: rank-TD
  alpha: 0.95
  batch_size: 32
  sampling: rank
loss: huber
mdp_size: 13
title: experience_replay=rank-TD; loss=huber; mdp_size=13
