_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  loss: mse
  mdp_size: 14
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
loss: mse
mdp_size: 14
title: experience_replay=uniform; loss=mse; mdp_size=14
