_experiment_parameters:
  experience_replay:
    __name: uniform-TD
    batch_size: 32
    sampling: uniform
  loss: huber
  mdp_size: 5
experience_replay:
  __name: uniform-TD
  batch_size: 32
  sampling: uniform
loss: huber
mdp_size: 5
title: experience_replay=uniform-TD; loss=huber; mdp_size=5
