_experiment_parameters:
  experience_replay:
    __name: rank-TD
    alpha: 0.95
    batch_size: 32
    sampling: rank
  loss: mse
  mdp_size: 11
experience_replay:
  __name: rank-TD
  alpha: 0.95
  batch_size: 32
  sampling: rank
loss: mse
mdp_size: 11
title: experience_replay=rank-TD; loss=mse; mdp_size=11
