_experiment_parameters:
  experience_replay:
    __name: uniform-TD
    batch_size: 32
    sampling: uniform
  loss: mse
  mdp_size: 12
experience_replay:
  __name: uniform-TD
  batch_size: 32
  sampling: uniform
loss: mse
mdp_size: 12
title: experience_replay=uniform-TD; loss=mse; mdp_size=12
