_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  loss: mse
  mdp_size: 5
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
loss: mse
mdp_size: 5
title: experience_replay=uniform; loss=mse; mdp_size=5
