mdp_size: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

reward_noise_precision: [0, 0.01, 0.1]

experience_replay:
  - {"__name": "rank-td", "batch_size": 32, "sampling": "rank", "alpha": 0.95}

  - {"__name": "rank-bayes-β0.001-p0.5",
     "sampling": "rank", "batch_size": 32, "alpha": 0.95,
     "bayesian": yes, "boot_p": 0.5, "boot_no": 21, "boot_beta": 0.001,
     "boot_shuffle": yes}

  - {"__name": "rank-bayes-β0.1-p0.5",
     "sampling": "rank", "batch_size": 32, "alpha": 0.95,
     "bayesian": yes, "boot_p": 0.5, "boot_no": 21, "boot_beta": 0.1,
     "boot_shuffle": yes}

  - {"__name": "rank-bayes-β2-p0.5",
     "sampling": "rank", "batch_size": 32, "alpha": 0.95,
     "bayesian": yes, "boot_p": 0.5, "boot_no": 21, "boot_beta": 2,
     "boot_shuffle": yes}
