_experiment_parameters:
  experience_replay:
    __name: proportional
    alpha: 1
    batch_size: 1
    sampling: proportional
  mdp_size: 11
experience_replay:
  __name: proportional
  alpha: 1
  batch_size: 1
  sampling: proportional
mdp_size: 11
title: experience_replay=proportional; mdp_size=11
