_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 1
    sampling: uniform
  mdp_size: 16
experience_replay:
  __name: uniform
  batch_size: 1
  sampling: uniform
mdp_size: 16
title: experience_replay=uniform; mdp_size=16
