_experiment_parameters:
  experience_replay:
    __name: greedy-pq
    batch_size: 1
    sampling: greedy-pq
  mdp_size: 3
experience_replay:
  __name: greedy-pq
  batch_size: 1
  sampling: greedy-pq
mdp_size: 3
title: experience_replay=greedy-pq; mdp_size=3
