_experiment_parameters:
  experience_replay:
    __name: rank-td
    alpha: 0.95
    batch_size: 32
    sampling: rank
  mdp_size: 6
experience_replay:
  __name: rank-td
  alpha: 0.95
  batch_size: 32
  sampling: rank
mdp_size: 6
title: experience_replay=rank-td; mdp_size=6
