_experiment_parameters:
  experience_replay:
    __name: "rank-bayes-\u03B20.01-p0.5"
    alpha: 0.95
    batch_size: 32
    bayesian: true
    boot_beta: 0.01
    boot_no: 21
    boot_p: 0.5
    boot_shuffle: true
    sampling: rank
  mdp_size: 12
experience_replay:
  __name: "rank-bayes-\u03B20.01-p0.5"
  alpha: 0.95
  batch_size: 32
  bayesian: true
  boot_beta: 0.01
  boot_no: 21
  boot_p: 0.5
  boot_shuffle: true
  sampling: rank
mdp_size: 12
title: "experience_replay=rank-bayes-\u03B20.01-p0.5; mdp_size=12"
