_experiment_parameters:
  experience_replay:
    __name: uniform-bayes-vote
    batch_size: 32
    bayesian: true
    boot_no: 20
    boot_p: 1
    boot_vote: true
    sampling: uniform
  mdp_size: 14
experience_replay:
  __name: uniform-bayes-vote
  batch_size: 32
  bayesian: true
  boot_no: 20
  boot_p: 1
  boot_vote: true
  sampling: uniform
mdp_size: 14
title: experience_replay=uniform-bayes-vote; mdp_size=14
