name: "Default"

mdp_size: 6

experience_replay:
  sampling: 'rank'
  batch_size: 32
  alpha: 0.8

  bayesian: no
  boot_no: 20
  boot_p: 0.9
  boot_vote: no
  boot_shuffle: yes
  boot_beta: 10

# mse or huber
loss: 'mse'
