_experiment_parameters:
  experience_replay:
    __name: uniform
    sampling: uniform
  mdp_size: 10
experience_replay:
  __name: uniform
  sampling: uniform
mdp_size: 10
title: experience_replay=uniform; mdp_size=10
