_experiment_parameters:
  experience_replay:
    __name: greedy-pq
    sampling: greedy-pq
  mdp_size: 16
experience_replay:
  __name: greedy-pq
  sampling: greedy-pq
mdp_size: 16
title: experience_replay=greedy-pq; mdp_size=16
