_experiment_parameters:
  experience_replay:
    __name: rank-bayes
    alpha: 0.8
    batch_size: 32
    bayesian: true
    boot_beta: 10
    boot_no: 20
    boot_p: 0.9
    boot_shuffle: false
    boot_vote: false
    sampling: rank
  mdp_size: 8
experience_replay:
  __name: rank-bayes
  alpha: 0.8
  batch_size: 32
  bayesian: true
  boot_beta: 10
  boot_no: 20
  boot_p: 0.9
  boot_shuffle: false
  boot_vote: false
  sampling: rank
mdp_size: 8
title: experience_replay=rank-bayes; mdp_size=8
