_experiment_parameters:
  experience_replay:
    __name: uniform
    batch_size: 32
    sampling: uniform
  mdp_size: 12
experience_replay:
  __name: uniform
  batch_size: 32
  sampling: uniform
mdp_size: 12
title: experience_replay=uniform; mdp_size=12
