_experiment_parameters:
  experience_replay:
    __name: rank-bayes-beta05
    alpha: 0.8
    batch_size: 32
    bayesian: true
    boot_beta: 0.5
    boot_no: 20
    boot_p: 0.9
    boot_shuffle: true
    boot_vote: false
    sampling: rank
  mdp_size: 2
experience_replay:
  __name: rank-bayes-beta05
  alpha: 0.8
  batch_size: 32
  bayesian: true
  boot_beta: 0.5
  boot_no: 20
  boot_p: 0.9
  boot_shuffle: true
  boot_vote: false
  sampling: rank
mdp_size: 2
title: experience_replay=rank-bayes-beta05; mdp_size=2
