_experiment_parameters:
  experience_replay:
    __name: rank
    alpha: 0.8
    batch_size: 32
    sampling: rank
  mdp_size: 9
experience_replay:
  __name: rank
  alpha: 0.8
  batch_size: 32
  sampling: rank
mdp_size: 9
title: experience_replay=rank; mdp_size=9
